
package interfaz.grafica.de.usuario;

public class InterfazGraficaDeUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public InterfazGraficaDeUsuario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        bgAutos = new javax.swing.ButtonGroup();
        etiquetaTxt = new javax.swing.JLabel();
        btnCambiaTexto = new javax.swing.JButton();
        btnTurn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ch_xb = new javax.swing.JCheckBox();
        ch_ns = new javax.swing.JCheckBox();
        consola = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        opcion2 = new javax.swing.JRadioButton();
        opcion1 = new javax.swing.JRadioButton();
        opcion3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        comboBoxAutos = new javax.swing.JComboBox<>();
        labelAuto = new javax.swing.JLabel();
        buttonConsulta = new javax.swing.JButton();
        labelNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        btnConsultaNombre = new javax.swing.JButton();
        txAreaButton = new javax.swing.JButton();
        labelTxArea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txArea = new javax.swing.JTextArea();
        passwordField = new javax.swing.JPasswordField();
        pfLabel = new javax.swing.JLabel();
        pfButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        LabelAge = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        EdadButton = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaTxt.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTxt.setText("jjj");
        etiquetaTxt.setAlignmentX(0.5F);
        etiquetaTxt.setAlignmentY(0.6F);
        etiquetaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etiquetaTxt.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        etiquetaTxt.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnCambiaTexto.setText("Cambia Texto");
        btnCambiaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiaTextoActionPerformed(evt);
            }
        });

        btnTurn.setText("Encender");
        btnTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnActionPerformed(evt);
            }
        });

        jLabel1.setText("Button");

        jLabel2.setText("Toggle Button");

        ch_xb.setText("Xbox");
        ch_xb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_xbActionPerformed(evt);
            }
        });

        ch_ns.setText("Switch");

        consola.setText("Consola");

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        bgAutos.add(opcion2);
        opcion2.setText("opcion2");

        bgAutos.add(opcion1);
        opcion1.setText("opcion1");

        bgAutos.add(opcion3);
        opcion3.setText("opcion3");
        opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion3ActionPerformed(evt);
            }
        });

        jLabel3.setText("RadioButton");

        comboBoxAutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ferrari", "Mustang", "BMW", "FORD" }));

        labelAuto.setText("Auto Seleccionado");

        buttonConsulta.setText("Consulta");
        buttonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultaActionPerformed(evt);
            }
        });

        labelNombre.setText("Tu nombre es");

        btnConsultaNombre.setText("Consulta");
        btnConsultaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaNombreActionPerformed(evt);
            }
        });

        txAreaButton.setText("Consulta");
        txAreaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAreaButtonActionPerformed(evt);
            }
        });

        labelTxArea.setText("Tu nombre es");
        labelTxArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txArea.setColumns(20);
        txArea.setRows(5);
        jScrollPane1.setViewportView(txArea);

        passwordField.setText("PasswordField");

        pfLabel.setText("Contraseña Revelada");

        pfButton.setText("Enviar");
        pfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Edad");

        LabelAge.setText("jLabel5");

        jButton1.setText("jButton1");

        EdadButton.setText("Enviar");
        EdadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnCambiaTexto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTurn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etiquetaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAuto)
                                .addGap(73, 73, 73))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcion2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(opcion1)
                                        .addGap(54, 54, 54)
                                        .addComponent(comboBoxAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonConsulta))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(opcion3)
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelAge)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(EdadButton)))))
                                .addContainerGap(22, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelTxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txAreaButton)
                                .addGap(99, 99, 99)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pfButton)
                                .addGap(18, 18, 18)
                                .addComponent(pfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultaNombre)
                                .addGap(36, 36, 36)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMostrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_xb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_ns)
                                .addGap(18, 18, 18)
                                .addComponent(consola)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labelAuto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcion1)
                            .addComponent(comboBoxAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonConsulta))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCambiaTexto)
                            .addComponent(btnTurn)
                            .addComponent(etiquetaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opcion2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opcion3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EdadButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch_xb)
                    .addComponent(ch_ns)
                    .addComponent(consola)
                    .addComponent(btnMostrar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultaNombre)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(LabelAge)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pfButton)
                        .addComponent(pfLabel))
                    .addComponent(txAreaButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiaTextoActionPerformed
        etiquetaTxt.setText("hola fucking");
    }//GEN-LAST:event_btnCambiaTextoActionPerformed

    private void btnTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnActionPerformed
        if (btnTurn.isSelected()){
            etiquetaTxt.setText("Encendido");
        }else{
            etiquetaTxt.setText("apagado");
        }
        
    }//GEN-LAST:event_btnTurnActionPerformed

    private void ch_xbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_xbActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_xbActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if(ch_xb.isSelected()){
            consola.setText("xbox epic");
        }else if(ch_ns.isSelected()){
            consola.setText("switch epic");
        }else{
            consola.setText("U stupid");
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcion3ActionPerformed

    private void buttonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultaActionPerformed
        // TODO add your handling code here:
        String auto;
        int selectedItem;
        selectedItem = comboBoxAutos.getSelectedIndex();
        auto = comboBoxAutos.getItemAt(selectedItem);
        labelAuto.setText(auto);
    }//GEN-LAST:event_buttonConsultaActionPerformed

    private void btnConsultaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaNombreActionPerformed
        String nombre = tfNombre.getText();
        labelNombre.setText(nombre);
// TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaNombreActionPerformed

    private void txAreaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAreaButtonActionPerformed
        String nombre=txArea.getText();// TODO add your h andling code here:
        labelTxArea.setText(nombre);
    }//GEN-LAST:event_txAreaButtonActionPerformed

    private void pfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfButtonActionPerformed
        // TODO add your handling code here:
        String contrasena = passwordField.getText();
        pfLabel.setText(contrasena);
    }//GEN-LAST:event_pfButtonActionPerformed

    private void EdadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadButtonActionPerformed
        String edad;
        edad = jSpinner1.getValue().toString();
        LabelAge.setText(edad);
// TODO add your handling code here:
    }//GEN-LAST:event_EdadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGraficaDeUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EdadButton;
    private javax.swing.JLabel LabelAge;
    private javax.swing.ButtonGroup bgAutos;
    private javax.swing.JButton btnCambiaTexto;
    private javax.swing.JButton btnConsultaNombre;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JToggleButton btnTurn;
    private javax.swing.JButton buttonConsulta;
    private javax.swing.JCheckBox ch_ns;
    private javax.swing.JCheckBox ch_xb;
    private javax.swing.JComboBox<String> comboBoxAutos;
    private javax.swing.JLabel consola;
    private static javax.swing.JLabel etiquetaTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelAuto;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTxArea;
    private javax.swing.JRadioButton opcion1;
    private javax.swing.JRadioButton opcion2;
    private javax.swing.JRadioButton opcion3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton pfButton;
    private javax.swing.JLabel pfLabel;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextArea txArea;
    private javax.swing.JButton txAreaButton;
    // End of variables declaration//GEN-END:variables
}
